name = "AgentsPlots"
uuid = "7820620d-95fb-4739-93b3-b0a14dd83f9a"
authors = ["Ali R. Vahdati", "George Datseris"]
version = "0.1.2"

[deps]
Agents = "46ada45e-f475-11e8-01d0-f70cc89e6671"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"

[compat]
julia = "1"
Agents = "2"
Plots = "0.28, 0.29"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
